const data={
  aves:{photos:20,pt:['Aves','Cores, cantos e movimentos que atravessam o céu do Pantanal.'],en:['Birds','Colors, calls and movement crossing the Pantanal sky.']},
  mamiferos:{photos:9,pt:['Mamíferos','Da onça-pintada à ariranha: encontros que ficam para sempre.'],en:['Mammals','From jaguars to giant otters: encounters that stay with you forever.']},
  repteis:{photos:9,pt:['Répteis','Habitantes antigos das águas, campos e matas pantaneiras.'],en:['Reptiles','Ancient inhabitants of the Pantanal waters, grasslands and forests.']},
  anfibios:{photos:9,pt:['Anfíbios','Pequenas vidas que anunciam a chuva e revelam a saúde do ambiente.'],en:['Amphibians','Small lives that announce the rain and reveal the health of the environment.']},
  invertebrados:{photos:9,pt:['Borboletas e outros invertebrados','Um universo delicado, quase invisível, sustentando toda a paisagem.'],en:['Butterflies & other invertebrates','A delicate, almost invisible universe supporting the entire landscape.']},
  plantas:{photos:9,pt:['Plantas','Flores, frutos e árvores que contam as estações do Pantanal.'],en:['Plants','Flowers, fruits and trees that tell the story of the Pantanal seasons.']}
};
const id=document.body.dataset.category;const item=data[id];let lang=localStorage.getItem('tchaco-language')==='en'?'en':'pt';
function render(){const [title,description]=item[lang];document.documentElement.lang=lang==='pt'?'pt-BR':'en';document.title=`${title} | Tchaco Pantaneiro`;document.querySelector('.back-link').innerHTML=`← ${lang==='pt'?'Voltar ao início':'Back to home'}`;document.querySelector('.category-kicker').textContent=lang==='pt'?'GALERIA DE CAMPO':'FIELD GALLERY';document.querySelector('.category-title').textContent=title;document.querySelector('.category-description').textContent=description;document.querySelector('.category-language').textContent=lang==='pt'?'EN':'PT';document.querySelector('.detail-grid').innerHTML=Array.from({length:item.photos},(_,i)=>i+2).map(n=>{const number=String(n).padStart(2,'0');return `<figure class="gallery-photo"><div class="slot-copy"><span>${lang==='pt'?'ARQUIVO DA IMAGEM':'IMAGE FILE'}</span><strong>assets/${id}-${number}.jpg</strong></div><img src="../assets/${id}-${number}.jpg" alt="${title} — ${n}" onload="this.parentElement.classList.add('has-image')" onerror="this.style.display='none'"></figure>`}).join('');document.querySelector('.footer-copy').textContent=lang==='pt'?'Guia registrado · CADASTUR · Pantanal, Brasil':'Registered guide · CADASTUR · Pantanal, Brazil';}
document.querySelector('.category-language').addEventListener('click',()=>{lang=lang==='pt'?'en':'pt';localStorage.setItem('tchaco-language',lang);render()});render();
