const classes = [
  {id:'aves',pt:['Aves','Cores, cantos e movimentos que atravessam o céu do Pantanal.'],en:['Birds','Colors, calls and movement crossing the Pantanal sky.']},
  {id:'mamiferos',pt:['Mamíferos','Da onça-pintada à ariranha: encontros que ficam para sempre.'],en:['Mammals','From jaguars to giant otters: encounters that stay with you forever.']},
  {id:'repteis',pt:['Répteis','Habitantes antigos das águas, campos e matas pantaneiras.'],en:['Reptiles','Ancient inhabitants of the Pantanal waters, grasslands and forests.']}
];
const copy={
  pt:{menu:['Sobre','Galerias','Contato'],eyebrow:'GUIA DE VIDA SELVAGEM · PANTANAL, BRASIL',hero:'O Pantanal<br>sem distância.',whatsapp:'Falar no WhatsApp',registered:'GUIA REGISTRADO',aboutKicker:'CONHEÇA SEU GUIA',aboutTitle:'Experiência de campo.<br>Olhar de quem pertence.',about1:'Tchaco Pantaneiro conduz experiências de observação de fauna no Pantanal, unindo conhecimento local, leitura da paisagem e respeito absoluto pela vida selvagem.',about2:'Guia de turismo registrado no CADASTUR, acompanha viajantes em busca dos encontros que só o Pantanal sabe oferecer.',archive:'ARQUIVO DE CAMPO',archiveTitle:'Conheça o Pantanal.',archiveIntro:'Escolha uma classe para abrir sua galeria completa.',contactKicker:'VIVA O PANTANAL',contactTitle:'O próximo encontro<br>começa aqui.',contactIntro:'Entre em contato diretamente com Tchaco Pantaneiro.',footer:'Guia registrado · CADASTUR · Pantanal, Brasil',video:'ARQUIVO DO VÍDEO',open:'Ver galeria completa'},
  en:{menu:['About','Galleries','Contact'],eyebrow:'WILDLIFE GUIDE · PANTANAL, BRAZIL',hero:'The Pantanal.<br>Up close.',whatsapp:'Message on WhatsApp',registered:'REGISTERED GUIDE',aboutKicker:'MEET YOUR GUIDE',aboutTitle:'Field experience.<br>The eye of a local.',about1:'Tchaco Pantaneiro leads wildlife-watching experiences in the Pantanal, combining local knowledge, an expert reading of the landscape and absolute respect for wildlife.',about2:'A licensed Brazilian tour guide registered with CADASTUR, he accompanies travelers in search of the encounters only the Pantanal can offer.',archive:'FIELD ARCHIVE',archiveTitle:'Discover the Pantanal.',archiveIntro:'Choose a class to open its complete gallery.',contactKicker:'EXPERIENCE THE PANTANAL',contactTitle:'Your next encounter<br>starts here.',contactIntro:'Contact Tchaco Pantaneiro directly.',footer:'Registered guide · CADASTUR · Pantanal, Brazil',video:'VIDEO FILE',open:'View complete gallery'}
};
function renderClasses(lang){
  document.querySelector('#gallery-root').innerHTML=`<div class="classes-grid">${classes.map((item,index)=>{const [title,description]=item[lang];return `<article class="class-preview"><div class="class-number">0${index+1}</div><h2>${title}</h2><p>${description}</p><figure class="image-slot class-video"><div class="slot-copy"><span>${copy[lang].video}</span><strong>assets/${item.id}-01.mp4</strong></div><video src="assets/${item.id}-01.mp4" aria-label="${title}" autoplay muted loop playsinline preload="metadata" onloadeddata="this.parentElement.classList.add('has-image')" onerror="this.style.display='none'"></video></figure><a class="class-link" href="${item.id}/">${copy[lang].open}<span>→</span></a></article>`}).join('')}</div>`;
}
function setLanguage(lang){
  const c=copy[lang];document.documentElement.lang=lang==='pt'?'pt-BR':'en';localStorage.setItem('tchaco-language',lang);
  document.querySelectorAll('.navlinks a').forEach((el,i)=>el.textContent=c.menu[i]);document.querySelector('.eyebrow').textContent=c.eyebrow;document.querySelector('.hero-copy h1').innerHTML=c.hero;
  const heroButtons=document.querySelectorAll('.hero-actions .button');heroButtons[0].textContent=c.whatsapp;document.querySelector('.cadastur-badge span').textContent=c.registered;
  const about=document.querySelector('.about-copy');about.querySelector('.section-kicker').textContent=c.aboutKicker;about.querySelector('h2').innerHTML=c.aboutTitle;const aboutP=about.querySelectorAll(':scope > p:not(.section-kicker)');aboutP[0].textContent=c.about1;aboutP[1].textContent=c.about2;
  const intro=document.querySelector('.gallery-intro');intro.querySelector('.section-kicker').textContent=c.archive;intro.querySelector('h2').innerHTML=c.archiveTitle;intro.querySelector('p:last-child').textContent=c.archiveIntro;
  const contact=document.querySelector('.contact');contact.querySelector('.section-kicker').textContent=c.contactKicker;contact.querySelector('h2').innerHTML=c.contactTitle;contact.querySelector('p:not(.section-kicker)').textContent=c.contactIntro;document.querySelector('footer > p:nth-of-type(1)').textContent=c.footer;
  document.querySelector('.language-toggle').textContent=lang==='pt'?'EN':'PT';renderClasses(lang);
}
const button=document.createElement('button');button.className='language-toggle';button.type='button';document.querySelector('.topbar').appendChild(button);
const style=document.createElement('style');style.textContent='.language-toggle{border:1px solid #ffffff73;background:#0a0b0959;color:#fff;min-width:48px;height:38px;padding:0 12px;font:700 .72rem Arial;letter-spacing:.12em;cursor:pointer}.language-toggle:hover,.class-link:hover{background:#b99858;color:#0a0b09}.classes-grid{max-width:1400px;margin:0 auto;padding:0 4vw 9rem;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.class-preview{border:1px solid #31332e;background:#12130f;padding:24px;display:flex;flex-direction:column}.class-number{color:#b99858;font:400 1rem Georgia}.class-preview h2{font-size:clamp(2rem,3.3vw,3.7rem);line-height:.95;margin:1rem 0}.class-preview>p{color:#9c9f96;line-height:1.6;min-height:78px}.class-video{width:min(100%,240px);aspect-ratio:478/850;min-height:0;margin:20px auto}.image-slot video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:0}.image-slot.has-image video{opacity:1}.class-link{margin-top:auto;border:1px solid #b99858;color:#b99858;min-height:50px;padding:0 16px;display:flex;align-items:center;justify-content:space-between;text-transform:uppercase;letter-spacing:.1em;font-size:.7rem;font-weight:700;transition:.25s}@media(max-width:950px){.classes-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.language-toggle{margin-left:auto}.classes-grid{grid-template-columns:1fr;padding:0 20px 6rem}.class-preview>p{min-height:0}.class-video{width:min(100%,220px)}}';document.head.appendChild(style);
let lang=localStorage.getItem('tchaco-language')==='en'?'en':'pt';button.addEventListener('click',()=>{lang=lang==='pt'?'en':'pt';setLanguage(lang)});
const whatsappIcon=document.querySelector('.floating-whatsapp svg');if(whatsappIcon){whatsappIcon.style.width='29px';whatsappIcon.style.height='29px';whatsappIcon.style.color='#fff'}setLanguage(lang);
